### ISSUE TITLE
CUDA Out of memory, had to lower batch size (Help with Memory Optimization)

### ISSUE THREAD

**Issue by Naman-Choudhary-AI-ML** [KimMeen/Time-LLM#19]
So just a general question, I had to lower batch size to get it to run, so can someone recomment memory optimization frameworks that I can utilize so that the model can run faster and take in more batch size, as currently the way its going, it will take days for the model to complete all epochs.

So need a bit of help in memory optimization, or if others are able to get it to work reasonably on Colab. I am currently running the TimeLLM_ETTh1.sh script, and it going too slow.

**Comment by KimMeen** [comment]
I believe there is room for such optimizations, and we welcome related pull requests. Alternatively, you may consider trying GPT-2. For more information, please see the issue at https://github.com/KimMeen/Time-LLM/issues/23

**Comment by ddwzs** [comment]
I trained scripts/TimeLLM_ETTh2.sh using 8 A100 40G GPUs, which took approximately 2 hours. Due to memory constraints, I adjusted the batch_size from 24 to 6, resulting in an effective batch_size of 6 * 8 = 48. The final Mean Squared Error (MSE) was 0.297, which is over 10% worse than the data in the paper, which reported an MSE of 0.268. This was based on training scripts/TimeLLM_ETTh2.sh for only ten epochs, while scripts/TimeLLM_ETTh1.sh requires training for 100 epochs, and the size of the traffic dataset is approximately 180 times that of ETTh2. The fact that such significant resource consumption is required for processing such a small dataset like ETTh significantly affects the feasibility of Time-LLM.

**Comment by lizhuoq** [comment]
I want to replace the backbone with GPT-2, which would significantly speed up the process while reducing memory consumption, as the parameter size of GPT-2 is much smaller than that of Llama2. Regarding the training approach, I wonder if it's feasible to pre-train on one dataset and then fine-tune for only a few epochs on another dataset.
